In [1]:
from data import Dataprocess
from tuning import Tuner
from predictor import Model
import numpy as np
import xgboost as xgb

In [2]:
dp = Dataprocess()
train_X, train_y, test_X = dp.process()
Model = Model()

In [4]:
test_y = Model.xgboost(train_X, train_y, test_X, num_boost_round=2000)

In [5]:
all_X = dp.mapper_X.transform(dp.df)

In [9]:
print "(Shape) all_X: ", all_X.shape,"and train_X: ",train_X.shape

(Shape) all_X:  (30697, 1956) and train_X:  (25697, 1956)


In [10]:
all_y = Model.xgboost(train_X, train_y, all_X, num_boost_round=2000)

In [11]:
print "(Shape) all_y: ", all_y.shape, "test_y: ", test_y.shape

(Shape) all_y:  (30697, 2) test_y:  (5000, 2)


In [28]:
plus_X = np.append(all_X, all_y, axis=1)

In [29]:
print "(Shape) plus_X:", plus_X.shape

(Shape) plus_X: (30697, 1958)


In [30]:
train_X_plus = plus_X[~np.isnan(dp.df["shot_made_flag"].as_matrix()), :]

In [31]:
train_X_plus.shape

(25697, 1958)

In [32]:
test_X_plus = plus_X[np.isnan(dp.df["shot_made_flag"].as_matrix()), :]

In [33]:
test_X_plus.shape

(5000, 1958)

In [34]:
test_y_plus = Model.xgboost(train_X_plus, train_y, test_X_plus,num_boost_round=2000)

In [35]:
Model.makesubmission(test_y_plus, savename="final_submit.csv")

In [20]:
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [21]:
a.shape

(4, 3)

In [22]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [23]:
b = np.array([[22,33],[24,25],[26,27],[28,29]])

In [24]:
b.shape

(4, 2)

In [25]:
b


array([[22, 33],
       [24, 25],
       [26, 27],
       [28, 29]])

In [26]:
c = np.append(a,b,axis =1)

In [27]:
c

array([[ 1,  2,  3, 22, 33],
       [ 4,  5,  6, 24, 25],
       [ 7,  8,  9, 26, 27],
       [10, 11, 12, 28, 29]])